name: Go Test
description: "Run Go Tests"

runs:
  using: "composite"
  steps:
    - name: Run Tests
      shell: bash
      run: |
        mkdir -p build
        go test ./... -count=1 -v -coverprofile=cover.out -coverpkg=./...
        cat cover.out | grep -v "mock_interface" | grep -v "migrations" > filteredCover.out

    - name: Coverage Report
      shell: bash
      run: |
        go tool cover -func=filteredCover.out -o=coverage.out

    - name: Extract Total Coverage Percentage
      shell: bash
      id: extract
      run: |
        LAST_LINE=$(tail -n 1 coverage.out)
        NUMBER=$(echo $LAST_LINE | awk -F '%' '{print $1}' | awk '{print $NF}')
        echo "percentage=$NUMBER" >> $GITHUB_ENV

    - name: Determine color
      shell: bash
      id: color
      run: |
        NUMBER=${{ env.percentage }}
        if (( $(echo "$NUMBER > 80" |bc -l) )); then
          echo "badge_color=green" >> $GITHUB_ENV
        elif (( $(echo "$NUMBER > 60" |bc -l) )); then
          echo "badge_color=yellow" >> $GITHUB_ENV
        else
          echo "badge_color=red" >> $GITHUB_ENV
        fi

    - name: Create Badge
      shell: bash
      run: |
        echo "badge=[![Coverage](https://img.shields.io/badge/Coverage-${{ env.percentage }}%25-${{ env.badge_color }})]()" >> $GITHUB_ENV

    - name: Update Badge in README
      shell: bash
      run: |
        BADGE_MARKER="<!-- COVERAGE BADGE -->"
        BADGE_CONTENT="${{ env.badge }}"
        if grep -q "$BADGE_MARKER" README.md; then
          perl -i -p0e "s|($BADGE_MARKER\n).*?(\n)|\1$BADGE_CONTENT\2|s" README.md
        else
          echo -e "\n$BADGE_MARKER\n$BADGE_CONTENT" >> README.md
        fi

    - name: Commit and push if changed
      shell: bash
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update README with extracted number" || exit 0
        git push
